# Generated by Django 5.0.6 on 2025-07-30 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_venta_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'tienda', 'talle')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='anulado_individualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),

        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
