# Generated by Django 5.0.6 on 2025-08-03 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a la venta total.', max_digits=5),
        ),
    ]
