# Generated by Django 5.0.6 on 2025-10-02 02:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_talle_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de descuento aplicado a la venta total.', max_digits=10),
        ),
    ]
