# Generated by Django 5.0.6 on 2025-10-19 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_detalleventa_costo_unitario_producto_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='es_financiero',
            field=models.BooleanField(default=False, help_text='Marcar si este método implica un arancel (Tarjeta, QR, etc.).'),
        ),
        migrations.AddField(
            model_name='venta',
            name='arancel_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total del arancel calculado para esta venta.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ArancelMetodoTienda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(choices=[('CONTADO', 'Contado / Pago Único'), ('1', '1 Cuota'), ('3', '3 Cuotas'), ('6', '6 Cuotas'), ('12', '12 Cuotas'), ('Z', 'Z (Ahora 12 / Plan Especial)')], default='CONTADO', max_length=20)),
                ('arancel_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Arancel en porcentaje (%) que la tienda paga al procesar este pago/plan.', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles_por_tienda', to='inventario.metodopago')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Arancel por Método y Tienda',
                'verbose_name_plural': 'Aranceles por Método y Tienda',
                'ordering': ['tienda', 'metodo_pago', 'nombre_plan'],
                'unique_together': {('tienda', 'metodo_pago', 'nombre_plan')},
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='arancel_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_con_arancel', to='inventario.arancelmetodotienda'),
        ),
    ]
