# Generated by Django 5.0.6 on 2025-12-27 00:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_metodopago_es_financiero_venta_arancel_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='api_key_arca',
            field=models.CharField(blank=True, help_text='API Key para integración con ARCA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='certificado_afip',
            field=models.TextField(blank=True, help_text='Certificado digital AFIP (.crt) codificado en base64', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='clave_privada_afip',
            field=models.TextField(blank=True, help_text='Clave privada AFIP (.key) codificado en base64', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='cuit',
            field=models.CharField(blank=True, help_text='CUIT de la tienda (formato: XX-XXXXXXXX-X)', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='modo_test_afip',
            field=models.BooleanField(default=True, help_text='Usar modo testing/homologación de AFIP'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='punto_venta',
            field=models.IntegerField(default=1, help_text='Punto de venta AFIP/ARCA'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_facturacion',
            field=models.CharField(choices=[('AFIP', 'AFIP (Administración Federal de Ingresos Públicos)'), ('ARCA', 'ARCA (Administración de Recursos de la Administración Nacional)'), ('NINGUNA', 'Sin facturación electrónica')], default='NINGUNA', help_text='Sistema de facturación a utilizar', max_length=10),
        ),
        migrations.AddField(
            model_name='tienda',
            name='url_arca',
            field=models.URLField(blank=True, help_text='URL del servicio ARCA', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_cuit',
            field=models.CharField(blank=True, help_text='CUIT del cliente', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_domicilio',
            field=models.CharField(blank=True, help_text='Domicilio del cliente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, help_text='Nombre o razón social del cliente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_tipo_documento',
            field=models.CharField(blank=True, help_text='Tipo de documento (DNI, CUIT, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='facturada',
            field=models.BooleanField(default=False, help_text='Indica si esta venta ha sido facturada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de recargo aplicado a la venta total.', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de recargo aplicado a la venta total.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='arancelmetodotienda',
            name='nombre_plan',
            field=models.CharField(choices=[('CONTADO', 'Contado / Pago Único'), ('1', '1 Cuota'), ('3', '3 Cuotas'), ('6', '6 Cuotas'), ('12', '12 Cuotas'), ('Z', 'Z (Plan Z)')], default='CONTADO', max_length=20),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_comprobante', models.IntegerField(blank=True, help_text='Número de comprobante asignado por AFIP/ARCA', null=True)),
                ('punto_venta', models.IntegerField(help_text='Punto de venta utilizado')),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Factura A (Responsable Inscripto)'), ('B', 'Factura B (Consumidor Final)'), ('C', 'Factura C (Exento)')], default='B', max_length=1)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('cliente_domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('EX', 'Exento'), ('MT', 'Monotributo'), ('NR', 'No Responsable')], default='CF', max_length=2)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('sistema_facturacion', models.CharField(choices=[('AFIP', 'AFIP (Administración Federal de Ingresos Públicos)'), ('ARCA', 'ARCA (Administración de Recursos de la Administración Nacional)'), ('NINGUNA', 'Sin facturación electrónica')], max_length=10)),
                ('cae', models.CharField(blank=True, help_text='CAE (Código de Autorización Electrónica) de AFIP', max_length=14, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, help_text='Fecha de vencimiento del CAE', null=True)),
                ('numero_comprobante_afip', models.BigIntegerField(blank=True, help_text='Número de comprobante retornado por AFIP', null=True)),
                ('respuesta_bruta', models.TextField(blank=True, help_text='Respuesta completa del servicio de facturación (JSON)', null=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si la facturación falló', null=True)),
                ('pdf_factura', models.FileField(blank=True, help_text='PDF de la factura generada', null=True, upload_to='facturas/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='inventario.tienda')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['tienda', 'numero_comprobante', 'punto_venta'], name='inventario__tienda__160d7b_idx'), models.Index(fields=['cae'], name='inventario__cae_7a2e2a_idx')],
            },
        ),
    ]
