# Generated by Django 5.0.6 on 2026-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_cambiodevolucion_detallecambiodevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='ml_access_token',
            field=models.TextField(blank=True, help_text='Access Token de Mercado Libre (obtenido mediante OAuth). No compartir públicamente.', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_app_id',
            field=models.CharField(blank=True, help_text='Application ID de Mercado Libre (Client ID)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret de Mercado Libre. No compartir públicamente.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_modo_test',
            field=models.BooleanField(default=True, help_text='Usar ambiente de testing/sandbox de Mercado Libre (True) o producción (False)'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_refresh_token',
            field=models.TextField(blank=True, help_text='Refresh Token de Mercado Libre para renovar el access token. No compartir públicamente.', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_sincronizar_precios',
            field=models.BooleanField(default=True, help_text='Sincronizar cambios de precios automáticamente con Mercado Libre'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_sincronizar_productos',
            field=models.BooleanField(default=True, help_text='Sincronizar nuevos productos automáticamente con Mercado Libre'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_sincronizar_stock',
            field=models.BooleanField(default=True, help_text='Sincronizar cambios de stock automáticamente con Mercado Libre'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_sync_habilitado',
            field=models.BooleanField(default=False, help_text='Habilitar sincronización automática de productos y stock con Mercado Libre'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del access token', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ml_user_id',
            field=models.CharField(blank=True, help_text='ID del usuario/vendedor en Mercado Libre', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='plataforma_ecommerce',
            field=models.CharField(choices=[('NINGUNA', 'Sin integración e-commerce'), ('MERCADO_LIBRE', 'Mercado Libre'), ('TIENDA_NUBE', 'Tienda Nube')], default='NINGUNA', help_text='Plataforma de e-commerce a integrar con esta tienda', max_length=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='api_key_arca',
            field=models.CharField(blank=True, help_text='API Key proporcionada por tu proveedor de servicios ARCA. Contacta a tu proveedor para obtenerla.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='certificado_afip',
            field=models.TextField(blank=True, help_text='⚠️ IMPORTANTE: Pega aquí el CONTENIDO COMPLETO del archivo .crt codificado en base64 (NO solo el nombre del archivo). Usa: python manage.py convertir_certificados_afip certificado.crt clave.key', null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='clave_privada_afip',
            field=models.TextField(blank=True, help_text='⚠️ IMPORTANTE: Pega aquí el CONTENIDO COMPLETO del archivo .key codificado en base64 (NO solo el nombre del archivo). Usa: python manage.py convertir_certificados_afip certificado.crt clave.key', null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='condicion_iva_emisor',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('CF', 'Consumidor Final'), ('EX', 'Exento'), ('NR', 'No Responsable')], default='MT', help_text='Condición frente al IVA del emisor (tienda). IMPORTANTE: Monotributistas SOLO pueden emitir Factura C. Responsables Inscriptos pueden emitir Factura A, B o C según el cliente.', max_length=2),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='modo_test_afip',
            field=models.BooleanField(default=True, help_text='Marca esta casilla para usar el ambiente de testing/homologación de AFIP. Desmarca para producción.'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='url_arca',
            field=models.URLField(blank=True, help_text='URL del endpoint del servicio ARCA. Ejemplo: https://api.arca.com/v1/facturacion. Consulta la documentación de tu proveedor.', null=True),
        ),
    ]
