# Generated by Django 5.0.6 on 2026-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_add_mercadolibre_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ml_item_id',
            field=models.CharField(blank=True, help_text='ID del producto en Mercado Libre (si está sincronizado)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ml_sincronizado',
            field=models.BooleanField(default=False, help_text='Indica si este producto está sincronizado con Mercado Libre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ml_ultima_sincronizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última sincronización con Mercado Libre', null=True),
        ),
    ]
