# Generated by Django 5.0.6 on 2026-01-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_fcmtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arancelmercadolibre',
            new_name='inventario__tienda__0017ec_idx',
            old_name='inventario_tienda__idx',
        ),
        migrations.RenameIndex(
            model_name='categoriamercadolibre',
            new_name='inventario__site_id_6a3244_idx',
            old_name='inventario_c_site_id_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='categoriamercadolibre',
            new_name='inventario__parent__3c052c_idx',
            old_name='inventario_c_parent_i_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmtoken',
            new_name='inventario__user_id_faed47_idx',
            old_name='inventario__user_id_activo_idx',
        ),
    ]
