# Generated by Django 5.0.6 on 2026-03-14 23:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_tienda_ml_facturar_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibido', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra de Stock',
                'verbose_name_plural': 'Compras de Stock',
                'ordering': ['-fecha_compra', '-fecha_creacion'],
            },
        ),
        migrations.RenameIndex(
            model_name='arancelmercadolibreproducto',
            new_name='inventario__tienda__3a8616_idx',
            old_name='inventario__tienda__aranc_ml_prod_idx',
        ),
        migrations.AlterField(
            model_name='arancelmetodotienda',
            name='nombre_plan',
            field=models.CharField(default='CONTADO', help_text='Plan predefinido o nombre personalizado', max_length=50),
        ),
        migrations.AddField(
            model_name='comprastock',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_stock', to='inventario.tienda'),
        ),
        migrations.AddField(
            model_name='comprastock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_stock_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
