# Generated by Django 5.0.6 on 2026-03-17 19:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_add_compra_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_comprobante', models.IntegerField(blank=True, null=True)),
                ('punto_venta', models.IntegerField()),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Nota de Crédito A (Responsable Inscripto)'), ('B', 'Nota de Crédito B (Consumidor Final)'), ('C', 'Nota de Crédito C (Exento/Monotributo)')], default='B', max_length=1)),
                ('motivo', models.TextField(blank=True, help_text='Motivo de la nota de crédito', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total de la nota de crédito (incluye IVA si aplica)', max_digits=10)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('sistema_facturacion', models.CharField(choices=[('AFIP', 'AFIP (Administración Federal de Ingresos Públicos)'), ('ARCA', 'ARCA (Administración de Recursos de la Administración Nacional)'), ('NINGUNA', 'Sin facturación electrónica')], max_length=10)),
                ('cae', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, null=True)),
                ('numero_comprobante_afip', models.BigIntegerField(blank=True, null=True)),
                ('respuesta_bruta', models.TextField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('factura_origen', models.ForeignKey(help_text='Factura electrónica original a la que se vincula esta nota de crédito', on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='inventario.factura')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
