# Generated by Django 5.0.6 on 2026-03-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_notacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='tn_access_token',
            field=models.TextField(blank=True, help_text='Access Token de Tienda Nube (obtenido mediante OAuth). No expira.', null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_app_id',
            field=models.CharField(blank=True, help_text='App ID de Tienda Nube (obtenido en el panel de partners)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret de Tienda Nube. No compartir públicamente.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_facturar_ventas',
            field=models.BooleanField(default=True, help_text='Facturar automáticamente ventas procesadas por webhook de Tienda Nube'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_store_id',
            field=models.CharField(blank=True, help_text='ID de la tienda en Tienda Nube (user_id del token exchange)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_sync_habilitado',
            field=models.BooleanField(default=False, help_text='Habilitar procesamiento automático de ventas desde Tienda Nube'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tn_webhook_id',
            field=models.CharField(blank=True, help_text='ID del webhook order/paid registrado en Tienda Nube', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='origen_tiendanube',
            field=models.BooleanField(default=False, help_text='True si la venta provino del webhook de Tienda Nube'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tn_order_id',
            field=models.CharField(blank=True, help_text='ID de la orden en Tienda Nube (para evitar duplicados)', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('tn_order_id__isnull', False)), fields=('tienda', 'tn_order_id'), name='unique_tn_order_per_tienda'),
        ),
    ]
