# Generated by Django 5.0.6 on 2026-03-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_tiendanube_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tn_product_id',
            field=models.CharField(blank=True, help_text='ID del producto en Tienda Nube', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tn_sincronizado',
            field=models.BooleanField(default=False, help_text='Indica si este producto está sincronizado con Tienda Nube'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tn_variant_id',
            field=models.CharField(blank=True, help_text='ID de la variante en Tienda Nube (usado para actualizar stock)', max_length=50, null=True),
        ),
    ]
