# Generated by Django 5.0.6 on 2026-04-06 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_tiendanube_producto_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ml_financing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo por ofrecer cuotas cobrado por Mercado Libre', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='ml_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo fijo por transacción cobrado por Mercado Libre', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='ml_sale_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cargo por venta (% comisión) cobrado por Mercado Libre', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='ml_tax_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuestos sobre los cargos de Mercado Libre', max_digits=10),
        ),
    ]
