# Generated by Django 5.0.6 on 2026-04-06 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_add_ml_fee_fields_to_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ml_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de envío real cobrado por Mercado Libre al vendedor (shipping.cost)', max_digits=10),
        ),
    ]
