# Generated by Django 5.0.6 on 2026-04-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_add_ml_shipping_cost_to_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ml_fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Fecha de entrega real al comprador (del webhook shipments de ML)', null=True),
        ),
    ]
