# Generated by Django 5.0.6 on 2026-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_add_ml_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tiendas_autorizadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_autorizados', to='inventario.tienda'),
        ),
    ]
