# Generated by Django 5.0.6 on 2026-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_user_tiendas_autorizadas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'tienda', 'talle')},
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_barras', 'tienda'), ('nombre', 'tienda', 'talle')},
        ),
    ]
