# Generated by Django 5.0.6 on 2026-04-28 23:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_barcode_unique_per_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cierre_caja_habilitado',
            field=models.BooleanField(default=False, help_text='Habilita el control de turnos y cierre de caja para este usuario'),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cambio_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billetes_20000', models.IntegerField(default=0)),
                ('billetes_10000', models.IntegerField(default=0)),
                ('billetes_2000', models.IntegerField(default=0)),
                ('billetes_1000', models.IntegerField(default=0)),
                ('billetes_500', models.IntegerField(default=0)),
                ('billetes_200', models.IntegerField(default=0)),
                ('billetes_100', models.IntegerField(default=0)),
                ('monedas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_ventas_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_egresos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_recuento_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_caja', to='inventario.tienda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='EgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EGRESO', 'Egreso / Gasto'), ('RETIRO', 'Retiro de caja'), ('PAGO_PROVEEDOR', 'Pago a proveedor')], default='EGRESO', max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cierre_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='inventario.cierrecaja')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_caja', to='inventario.tienda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso de Caja',
                'verbose_name_plural': 'Egresos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
