# Generated by Django 5.0.6 on 2026-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_cierre_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo EGRESO/Gasto (impacta métricas)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_ingresos_extra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos de efectivo extra (no impacta métricas)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_retiros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retiros de caja (no impacta métricas)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='total_egresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total salidas de caja (gastos + retiros)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='egresocaja',
            name='tipo',
            field=models.CharField(choices=[('EGRESO', 'Gasto'), ('RETIRO', 'Retiro de caja'), ('INGRESO', 'Ingreso de efectivo')], default='EGRESO', max_length=20),
        ),
    ]
