# Generated by Django 5.0.6 on 2026-05-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_tienda_ml_aranceles_automaticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Supervisor: puede ver ventas completas, agregar productos y ver cierres de caja'),
        ),
    ]
