# Generated by Django 5.0.6 on 2026-05-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_add_is_supervisor_to_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['venta', 'anulado_individualmente'], name='detalle_venta_anulado_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tienda'], name='producto_tienda_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tienda', 'fecha_venta'], name='venta_tienda_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tienda', 'anulada'], name='venta_tienda_anulada_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario'], name='venta_usuario_idx'),
        ),
    ]
