# Generated by Django 5.0.6 on 2026-05-13 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_padre',
            field=models.ForeignKey(blank=True, help_text='Producto padre del que esta variante forma parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='inventario.producto'),
        ),
    ]
