# Generated by Django 5.0.6 on 2026-05-15 13:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_producto_padre_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('advanced', 'Advanced')], max_length=20, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_productos', models.IntegerField(blank=True, null=True)),
                ('max_usuarios', models.IntegerField(blank=True, null=True)),
                ('permite_factura_electronica', models.BooleanField(default=False)),
                ('permite_integracion_ecommerce', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('trial', 'Período de prueba'), ('activa', 'Activa'), ('gracia', 'Período de gracia'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='trial', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_trial', models.DateTimeField(blank=True, null=True)),
                ('fecha_proximo_cobro', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_gracia', models.DateTimeField(blank=True, null=True)),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='inventario.plan')),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
