# Generated by Django 5.0.6 on 2026-07-17 16:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_metodo_pago_cuenta_corriente(apps, schema_editor):
    MetodoPago = apps.get_model('inventario', 'MetodoPago')
    MetodoPago.objects.update_or_create(
        nombre='Cuenta Corriente',
        defaults={
            'es_financiero': False,
            'activo': True,
            'descripcion': 'Venta a crédito: el pago queda pendiente en la cuenta corriente del cliente.',
        },
    )


def remove_metodo_pago_cuenta_corriente(apps, schema_editor):
    MetodoPago = apps.get_model('inventario', 'MetodoPago')
    MetodoPago.objects.filter(nombre='Cuenta Corriente').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0053_seed_plan_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('cuit_cuil', models.CharField(max_length=13)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_razon_social'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='inventario.cliente'),
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCorriente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito (venta a cuenta)'), ('CREDITO', 'Crédito (pago / anulación)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_corriente', to='inventario.cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cuenta_corriente', to='inventario.tienda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta_corriente', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta_corriente', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta Corriente',
                'verbose_name_plural': 'Movimientos de Cuenta Corriente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tienda', 'cuit_cuil'], name='inventario__tienda__274565_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tienda', 'cuit_cuil')},
        ),
        migrations.AddIndex(
            model_name='movimientocuentacorriente',
            index=models.Index(fields=['cliente', 'fecha'], name='inventario__cliente_5a56ca_idx'),
        ),
        migrations.RunPython(seed_metodo_pago_cuenta_corriente, remove_metodo_pago_cuenta_corriente),
    ]
