# Generated by Django 5.0.6 on 2026-07-17 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_seed_cliente_cuenta_corriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_barras', 'tienda'), ('codigo_interno', 'tienda'), ('nombre', 'tienda', 'talle')},
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
                'unique_together': {('tienda', 'nombre')},
            },
        ),
    ]
