# Generated by Django 5.0.6 on 2026-07-17 23:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_carga_masiva_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONVERTIDO', 'Convertido en Venta'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago_sugerido', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('recargo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('recargo_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='inventario.cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='inventario.tienda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_generados', to=settings.AUTH_USER_MODEL)),
                ('venta_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_origen', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_presupuesto', to='inventario.producto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['tienda', 'fecha_creacion'], name='presupuesto_tienda_fecha_idx'),
        ),
    ]
