# Generated by Django 5.0.6 on 2026-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0056_presupuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual el presupuesto es válido.', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, help_text='Fecha límite para cancelar el pago (Cuenta Corriente).', null=True),
        ),
    ]
