# Generated by Django 5.0.6 on 2026-07-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0057_presupuesto_vigencia_venta_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.rubro'),
        ),
    ]
