# Generated by Django 5.0.6 on 2026-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0058_producto_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cae',
            field=models.CharField(blank=True, help_text='CAE (Código de Autorización Electrónica) de ARCA', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_comprobante',
            field=models.IntegerField(blank=True, help_text='Número de comprobante asignado por ARCA', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_comprobante_afip',
            field=models.BigIntegerField(blank=True, help_text='Número de comprobante retornado por ARCA', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sistema_facturacion',
            field=models.CharField(choices=[('AFIP', 'ARCA (ex AFIP) — Agencia de Recaudación y Control Aduanero'), ('ARCA', 'ARCA (alternativa, sin integración implementada)'), ('NINGUNA', 'Sin facturación electrónica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='sistema_facturacion',
            field=models.CharField(choices=[('AFIP', 'ARCA (ex AFIP) — Agencia de Recaudación y Control Aduanero'), ('ARCA', 'ARCA (alternativa, sin integración implementada)'), ('NINGUNA', 'Sin facturación electrónica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ml_facturar_ventas',
            field=models.BooleanField(default=True, help_text='Si está activo, las ventas procesadas por el webhook de Mercado Libre se facturan automáticamente (ARCA). Si está desactivado, solo se emite recibo (no se genera factura electrónica).'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='modo_test_afip',
            field=models.BooleanField(default=True, help_text='Marca esta casilla para usar el ambiente de testing/homologación de ARCA. Desmarca para producción.'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='punto_venta',
            field=models.IntegerField(default=1, help_text='Punto de venta ARCA'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='tipo_facturacion',
            field=models.CharField(choices=[('AFIP', 'ARCA (ex AFIP) — Agencia de Recaudación y Control Aduanero'), ('ARCA', 'ARCA (alternativa, sin integración implementada)'), ('NINGUNA', 'Sin facturación electrónica')], default='NINGUNA', help_text='Sistema de facturación a utilizar', max_length=10),
        ),
    ]
