# Generated by Django 5.0.6 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0059_arca_rename_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='requiere_eleccion_plan',
            field=models.BooleanField(default=False, help_text='Fuerza a esta tienda (aunque sea legacy) a elegir y pagar un plan para poder seguir usando el sistema. No afecta a otras tiendas legacy.'),
        ),
    ]
