# Generated by Django 5.0.6 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0060_tienda_requiere_eleccion_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente de pago'), ('trial', 'Período de prueba'), ('activa', 'Activa'), ('gracia', 'Período de gracia'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='trial', max_length=20),
        ),
    ]
