# Generated by Django 5.0.6 on 2026-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0061_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo de la tienda como data URI en base64 (ya redimensionado a un tamaño chico desde el frontend antes de subir). Se muestra en el navbar.', null=True),
        ),
    ]
