# Generated by Django 5.0.6 on 2026-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0062_tienda_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionTiendaNubePendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('tn_store_id', models.CharField(max_length=50)),
                ('tn_access_token', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instalación pendiente de Tienda Nube',
                'verbose_name_plural': 'Instalaciones pendientes de Tienda Nube',
            },
        ),
    ]
