# Generated by Django 5.0.6 on 2026-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0063_instalaciontiendanubependiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaccion',
            name='accion',
            field=models.CharField(choices=[('anulacion_venta', 'Anulación de venta'), ('anulacion_item', 'Anulación de ítem'), ('ingreso_stock', 'Ingreso de stock'), ('ajuste_stock', 'Ajuste de stock'), ('cambio_devolucion', 'Cambio / Devolución'), ('transferencia_stock', 'Transferencia de stock')], max_length=30),
        ),
    ]
