# Generated by Django 5.0.6 on 2026-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0064_transferencia_stock_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='tn_facturar_ventas',
            field=models.BooleanField(default=False, help_text='Facturar automáticamente ventas procesadas por webhook de Tienda Nube'),
        ),
    ]
