# Generated by Django 5.0.6 on 2026-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0065_alter_tienda_tn_facturar_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='descuento_efectivo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de descuento por pago en efectivo a mostrar destacado en las etiquetas de precio. Null = no se muestra por defecto.', max_digits=5, null=True),
        ),
    ]
