# Generated by Django 5.0.6 on 2026-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_agregar_descuento_efectivo_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='descuento_efectivo_redondeo',
            field=models.CharField(blank=True, choices=[('', 'Sin redondeo'), ('abajo', 'Múltiplo de 100 hacia abajo'), ('arriba', 'Múltiplo de 100 hacia arriba')], default='', help_text='Cómo redondear el precio con descuento en efectivo calculado para las etiquetas (igual que el redondeo de Punto de Venta).', max_length=10),
        ),
    ]
