# Generated by Django 5.0.6 on 2026-08-14 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0067_agregar_redondeo_descuento_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiodevolucion',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cambiodevolucion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='cambiodevolucion',
            name='recargo_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cambiodevolucion',
            name='recargo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='monto_diferencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia bruta (sin descuento/recargo): positivo = cliente debe pagar, negativo = saldo a favor del cliente', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='monto_nuevo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de productos nuevos recibidos en el cambio (precio de catálogo, sin descuento/recargo)', max_digits=10),
        ),
    ]
