# Generated by Django 5.0.6 on 2026-08-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0068_agregar_descuento_recargo_cambio_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='widget_token',
            field=models.CharField(blank=True, help_text='Token de solo lectura para el widget de iPhone (ventas del día). Separado del login: se puede regenerar sin afectar la cuenta.', max_length=64, null=True, unique=True),
        ),
    ]
