# Generated by Django 5.0.6 on 2026-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0069_tienda_widget_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.TextField(blank=True, help_text='Foto del producto como data URI en base64 (ya redimensionada a un tamaño chico desde el frontend antes de subir). Se muestra en el listado y en el carrito de Punto de Venta.', null=True),
        ),
    ]
