# Generated by Django 5.0.6 on 2026-08-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0069_tienda_widget_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tienda', 'nombre'], name='producto_tienda_nombre_idx'),
        ),
    ]
