# Generated by Django 5.0.6 on 2026-08-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0070_producto_imagen'),
        ('inventario', '0071_agregar_indice_tienda_nombre_producto'),
    ]

    operations = [
    ]
