# Generated by Django 5.0.6 on 2026-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0072_merge_20260825_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_barras', 'tienda'), ('codigo_interno', 'tienda')},
        ),
        migrations.AddField(
            model_name='producto',
            name='variante2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_barras', 'tienda'), ('codigo_interno', 'tienda'), ('nombre', 'tienda', 'talle', 'variante2')},
        ),
    ]
