# Generated by Django 5.0.6 on 2026-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0073_producto_variante2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ml_catalog_product_id',
            field=models.CharField(blank=True, help_text='ID de producto de Catálogo de Mercado Libre, compartido por todas las publicaciones (propias) del mismo producto -- se usa para agrupar/crear variantes.', max_length=50, null=True),
        ),
    ]
