# Generated by Django 5.0.6 on 2026-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0074_producto_ml_catalog_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ml_stock_full',
            field=models.BooleanField(default=False, help_text='True si la publicación de Mercado Libre usa logística Full (el stock vive en los depósitos de ML, no en el del vendedor).'),
        ),
    ]
