# Generated by Django 5.0.6 on 2026-08-31 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0075_producto_ml_stock_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='hereda_suscripcion_de',
            field=models.ForeignKey(blank=True, help_text='Si se completa, el acceso de esta tienda (activa/pausada/cancelada) sigue al estado de la Suscripcion de la tienda referenciada en vez de tener una propia. Uso: una segunda tienda sin costo (ej. otra cuenta de Mercado Libre del mismo cliente) que debe bloquearse si se da de baja la tienda principal que sí paga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_dependientes', to='inventario.tienda'),
        ),
    ]
