# Generated by Django 5.0.6 on 2026-08-31 14:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0076_tienda_hereda_suscripcion_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arancelmercadolibreproducto',
            name='arancel_porcentaje',
        ),
        migrations.AddField(
            model_name='arancelmercadolibreproducto',
            name='cargo_por_vender',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Cargo fijo por vender este producto (por unidad)', max_digits=10),
        ),
        migrations.AddField(
            model_name='arancelmercadolibreproducto',
            name='costo_por_unidad_vendida',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo fijo por unidad vendida', max_digits=10),
        ),
        migrations.AddField(
            model_name='arancelmercadolibreproducto',
            name='impuestos_estimados',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Impuestos estimados por unidad vendida', max_digits=10),
        ),
        migrations.AlterField(
            model_name='arancelmercadolibreproducto',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo de envío estimado por unidad de este producto', max_digits=10),
        ),
    ]
