# Generated by Django 5.0.6 on 2026-08-31 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0077_remove_arancelmercadolibreproducto_arancel_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arancelmercadolibreproducto',
            name='cargo_por_vender',
        ),
        migrations.RemoveField(
            model_name='arancelmercadolibreproducto',
            name='costo_por_unidad_vendida',
        ),
        migrations.RemoveField(
            model_name='arancelmercadolibreproducto',
            name='impuestos_estimados',
        ),
        migrations.AddField(
            model_name='arancelmercadolibreproducto',
            name='impuestos_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Impuestos estimados, en % sobre el subtotal vendido de este producto', max_digits=5),
        ),
    ]
