# Generated by Django 5.0.6 on 2026-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0079_proveedor_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='se_vende_por_peso',
            field=models.BooleanField(default=False),
        ),
    ]
