# Generated by Django 5.0.6 on 2026-09-05 19:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0080_producto_se_vende_por_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArancelTiendaNube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(help_text="Slug del medio de pago tal cual lo manda Tienda Nube (ej: 'gocuotas', 'mercadopago', 'modo').", max_length=50)),
                ('gateway_nombre', models.CharField(blank=True, default='', help_text="Nombre para mostrar (ej: 'GOcuotas'). Solo informativo.", max_length=100)),
                ('criterio', models.CharField(blank=True, choices=[('', 'Todos los medios'), ('DEBITO', 'Tarjeta de débito'), ('CREDITO', 'Tarjeta de crédito')], default='', help_text="Dejar en 'Todos los medios' salvo que este gateway cobre distinto según débito/crédito.", max_length=10)),
                ('tasa_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa (%) que cobra el medio de pago, antes de IVA.', max_digits=5)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='IVA (%) que se suma sobre la tasa.', max_digits=5)),
                ('cpt_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CPT: costo (%) por cobrar el dinero de forma anticipada, si el plan elegido lo tiene.', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles_tn', to='inventario.tienda')),
            ],
            options={
                'verbose_name': 'Arancel Tienda Nube',
                'verbose_name_plural': 'Aranceles Tienda Nube',
                'ordering': ['tienda', 'gateway', 'criterio'],
                'unique_together': {('tienda', 'gateway', 'criterio')},
            },
        ),
    ]
