# Generated by Django 5.0.6 on 2026-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0081_aranceltiendanube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aranceltiendanube',
            name='criterio',
            field=models.CharField(blank=True, choices=[('', 'Todos los medios'), ('DEBITO', 'Tarjeta de débito'), ('CREDITO', 'Tarjeta de crédito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('BILLETERA', 'Billetera virtual')], default='', help_text="Dejar en 'Todos los medios' salvo que este gateway cobre distinto según el medio de pago.", max_length=13),
        ),
    ]
