# Generated by Django 5.0.6 on 2026-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0082_alter_aranceltiendanube_criterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mp_authorized_payment_id',
            field=models.CharField(blank=True, help_text='ID del pago autorizado de Mercado Pago (para evitar duplicados)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='origen_mp_suscripcion',
            field=models.BooleanField(default=False, help_text='True si la venta representa el cobro de una suscripción de un cliente de Total Stock'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('mp_authorized_payment_id__isnull', False)), fields=('tienda', 'mp_authorized_payment_id'), name='unique_mp_authorized_payment_per_tienda'),
        ),
    ]
