# Generated by Django 5.0.6 on 2026-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0084_producto_orden_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_variable',
            field=models.BooleanField(default=False),
        ),
    ]
