# Generated by Django 5.0.6 on 2026-09-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0085_producto_precio_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_fraccionada',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('METRO', 'Metro')], default='KG', max_length=10),
        ),
    ]
