# Generated by Django 5.0.6 on 2026-09-14 21:41

from django.db import migrations, models


PLAN_FREE = {
    'nombre': 'free',
    'precio_mensual': '0.00',
    'max_productos': 50,
    'max_usuarios': 1,
    'max_ventas_diarias': 10,
    'permite_factura_electronica': False,
    'permite_integracion_ecommerce': False,
    'mp_plan_id': '',
}


def seed_plan_free(apps, schema_editor):
    Plan = apps.get_model('inventario', 'Plan')
    Plan.objects.update_or_create(nombre=PLAN_FREE['nombre'], defaults=PLAN_FREE)


def remove_plan_free(apps, schema_editor):
    Plan = apps.get_model('inventario', 'Plan')
    Plan.objects.filter(nombre='free').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0086_producto_unidad_fraccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_ventas_diarias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('advanced', 'Advanced'), ('legacy', 'Legacy (sin restricciones)')], max_length=20, unique=True),
        ),
        migrations.RunPython(seed_plan_free, remove_plan_free),
    ]
