# Generated by Django 5.0.6 on 2026-09-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0087_plan_free_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='pago_atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
