# Generated by Django 5.0.6 on 2026-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0088_suscripcion_pago_atrasado'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='limite_productos_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
