# Generated by Django 5.0.6 on 2026-09-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0089_suscripcion_limite_productos_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Observación de la venta (Cuenta Corriente), ej. quién retira la mercadería.', max_length=120, null=True),
        ),
    ]
