# Generated by Django 5.0.6 on 2026-09-19 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0090_venta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dia_cierre_cuenta_corriente',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes (1-31) de cierre de cuenta corriente. Vacío = pedir la fecha a mano en cada venta.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
