# Generated by Django 5.0.6 on 2026-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0091_cliente_dia_cierre_cuenta_corriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='tn_location_id',
            field=models.CharField(blank=True, help_text='ID de la location (centro de distribución) por defecto en Tienda Nube, para sincronizar stock en tiendas multi-inventory', max_length=50, null=True),
        ),
    ]
