# Generated by Django 5.0.6 on 2026-09-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0093_indices_busqueda_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='tn_webhook_cancelado_id',
            field=models.CharField(blank=True, help_text='ID del webhook order/cancelled registrado en Tienda Nube (para poder borrarlo al desconectar)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tn_order_number',
            field=models.CharField(blank=True, help_text='Número de pedido (order.number) tal cual lo ve el comerciante en Tienda Nube -- para mostrar en vez de tn_order_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tn_order_id',
            field=models.CharField(blank=True, help_text='ID interno (order.id) de la orden en Tienda Nube -- usado solo para detectar duplicados, no se lo mostramos al comerciante (ver tn_order_number)', max_length=50, null=True),
        ),
    ]
