# Generated by Django 5.0.6 on 2026-10-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0094_tienda_tn_webhook_cancelado_id_venta_tn_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta (si el pago fue con tarjeta).', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Observación de la venta, ej. quién retira la mercadería.', max_length=120, null=True),
        ),
    ]
