# Generated by Django 5.0.6 on 2026-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0095_venta_numero_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('NARANJA_X', 'Naranja X'), ('AMEX', 'Amex')], help_text='Marca de la tarjeta (si el pago fue con tarjeta).', max_length=20, null=True),
        ),
    ]
