# Generated by Django 5.0.6 on 2026-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0096_venta_tipo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ventas_consolidadas',
            field=models.ManyToManyField(blank=True, related_name='facturas_consolidadas', to='inventario.venta'),
        ),
    ]
