name = "ml-oauth-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Secrets (configurar con: wrangler secret put ML_OAUTH_BACKEND_URL)
# - ML_OAUTH_BACKEND_URL
# - ML_OAUTH_WORKER_SECRET
